### ISSUE TITLE
Python-Fehler führt zu Abbruch der Installation auf 1.0.10

### ISSUE THREAD

**Issue by britter-decoit** [decoit/asterisk4ucs#15]
Beim Installieren nach dem Einspielen der Pull-Requests #13 und #14 tritt beim Installieren des Pakets astersik4ucs-testasterisk folgender Fehler auf.

```
asterisk4ucs-testasterisk (1.0.1) wird eingerichtet ...
create ssh-key...
copy ssh-key...
creating known_hosts entry...
create udm object for Testserver...
Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 222, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/pymodules/python2.7/univention/admincli/admin.py", line 404, in doit
    out = _doit(arglist)
  File "/usr/lib/pymodules/python2.7/univention/admincli/admin.py", line 746, in _doit
    dn = object.create()
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/__init__.py", line 306, in create
    return self._create()
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/__init__.py", line 765, in _create
    self._ldap_post_create()
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/asterisk/server.py", line 339, in _ldap_post_create
    defaultMoh = music.object(self.co, self.lo, pos, None, self)
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/asterisk/__init__.py", line 590, in __init__
    super(AsteriskBase, self).__init__(co, lo, position, dn, self.superordinate, attributes)
AttributeError: 'object' object has no attribute 'superordinate'
```

Der Fehler stammt aus dieser Datei: https://github.com/decoit/asterisk4ucs/blob/ucs4.1/asterisk4ucs-udm/modules/univention/admin/handlers/asterisk/__init__.py#L590

**Comment by spaceone** [comment]
Ja, dazu muss erst noch https://forge.univention.org/bugzilla/show_bug.cgi?id=43423 veröffentlicht werden.

**Comment by britter-decoit** [comment]
Fehler ist mit Pull Request #16 korrigiert.
