### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'getAttr'

### ISSUE THREAD

**Issue by spaceone** [decoit/asterisk4ucs#19]
We received the following external feedback:

Version: UCS 4.2-0 errata2 (Lesum)
```
Die Ausführung des Kommandos udm/add asterisk/asterisk ist fehlgeschlagen:

Traceback (most recent call last):
  File "%PY2.7%/notifier/threads.py", line 82, in _run
    tmp = self._function()
  File "%PY2.7%/notifier/__init__.py", line 104, in __call__
    return self._function( *tmp, **self._kwargs )
  File "%PY2.7%/univention/management/console/modules/udm/__init__.py", line 368, in _thread
    dn = module.create(properties, container=options.get('container'), superordinate=options.get('superordinate'))
  File "%PY2.7%/univention/management/console/modules/udm/udm_ldap.py", line 86, in _decorated
    return method(*args, **kwargs)
  File "%PY2.7%/univention/management/console/ldap.py", line 143, in _decorated
    result = func(*args, **kwargs)
  File "%PY2.7%/univention/management/console/modules/udm/udm_ldap.py", line 372, in create
    obj = self.module.object(None, ldap_connection, ldap_position, superordinate=superordinate)
  File "%PY2.7%/univention/admin/handlers/asterisk/phoneGroup.py", line 90, in __init__
    super(object, self).__init__(self, co, lo, position, dn, superordinate)
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 585, in __init__
    self.openSuperordinate()
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 622, in openSuperordinate
    serverdn = self.oldattr.get("ast4ucsSrvchildServer") or self.lo.getAttr(self.dn, "ast4ucsSrvchildServer")
AttributeError: 'NoneType' object has no attribute 'getAttr'
```

**Comment by spaceone** [comment]
This has been reported again by a customer which uses UCS 4.2-2 errata203 (Lesum).

**Comment by spaceone** [comment]
It has been reported again with UCS 4.2-2 errata204 (Lesum).

**Comment by MerKki** [comment]
This has been reported again with UCS 4.2-2 errata231 (Lesum).
