### ISSUE TITLE
asteriskMusic/queryMohs raises noObject exception

### ISSUE THREAD

**Issue by spaceone** [decoit/asterisk4ucs#20]
We received the following feedback:

Version: 4.2-0 errata10 (Lesum)
```
Die Ausführung des Kommandos asteriskMusic/queryMohs ist fehlgeschlagen:
Traceback (most recent call last):
  File "%PY2.7%/univention/management/console/base.py", line 249, in execute
    function.__func__(self, request, *args, **kwargs)
  File "%PY2.7%/univention/management/console/modules/asteriskMusic/__init__.py", line 61, in queryMohs
    mohs = getMohs()
  File "%PY2.7%/univention/management/console/modules/asteriskMusic/__init__.py", line 180, in getMohs
    mohs = music.lookup(co, lo, None)
  File "%PY2.7%/univention/admin/handlers/asterisk/music.py", line 90, in lookup
    superordinate=superordinate, attributes=attrs))
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 585, in __init__
    self.openSuperordinate()
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 631, in openSuperordinate
    self.superordinate = servermod.object(self.co, self.lo, self.position, serverdn)
  File "%PY2.7%/univention/admin/handlers/__init__.py", line 584, in __init__
    raise univention.admin.uexceptions.noObject(self.dn)
noObject: cn=Lokaler Testserver,cn=asterisk,dc=molekular,dc=intranet
```

**Comment by spaceone** [comment]
Reported again. Version: 4.2-1 errata122 (Lesum).

Maybe the error handling at the point where this object is created is wrong?

**Comment by spaceone** [comment]
Another report: Version: 4.2-1 errata122 (Lesum)
Happened on a Domaincontroller Backup.

```
Die Ausführung des Kommandos asteriskDeploy/create ist fehlgeschlagen:

Traceback (most recent call last):
  File "%PY2.7%/univention/management/console/base.py", line 249, in execute
    function.__func__(self, request, *args, **kwargs)
  File "%PY2.7%/univention/management/console/modules/asteriskDeploy/__init__.py", line 65, in create
    createConfigs(log, server)
  File "%PY2.7%/univention/management/console/modules/asteriskDeploy/__init__.py", line 150, in createConfigs
    configs = univention.admin.handlers.asterisk.genConfigs(server)
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 529, in genConfigs
    'musiconhold.conf': genMusiconholdconf(co, lo, server),
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 266, in genMusiconholdconf
    for moh in music.lookup(co, lo, False):
  File "%PY2.7%/univention/admin/handlers/asterisk/music.py", line 90, in lookup
    superordinate=superordinate, attributes=attrs))
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 585, in __init__
    self.openSuperordinate()
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 631, in openSuperordinate
    self.superordinate = servermod.object(self.co, self.lo, self.position, serverdn)
  File "%PY2.7%/univention/admin/handlers/__init__.py", line 633, in __init__
    raise univention.admin.uexceptions.noObject(self.dn)
noObject: cn=Lokaler Testserver,cn=asterisk,dc=intern,dc=*****,dc=de
```
