### ISSUE TITLE
AttributeError: 'str' object has no attribute 'module'

### ISSUE THREAD

**Issue by spaceone** [decoit/asterisk4ucs#21]
We received the following feedback:
Version: 4.2-0 errata10 (Lesum)
```
Die Ausführung des Kommandos asteriskDeploy/create ist fehlgeschlagen:

Traceback (most recent call last):
  File "%PY2.7%/univention/management/console/base.py", line 249, in execute
    function.__func__(self, request, *args, **kwargs)
  File "%PY2.7%/univention/management/console/modules/asteriskDeploy/__init__.py", line 70, in create
    createConfigs(log, server)
  File "%PY2.7%/univention/management/console/modules/asteriskDeploy/__init__.py", line 156, in createConfigs
    configs = univention.admin.handlers.asterisk.genConfigs(server)
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 528, in genConfigs
    'queues.conf': genQueuesconf(co, lo, server),
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 237, in genQueuesconf
    for queue in waitingLoop.lookup(co, lo, False):
  File "%PY2.7%/univention/admin/handlers/asterisk/waitingLoop.py", line 172, in lookup
    superordinate=superordinate, attributes=attrs))
  File "%PY2.7%/univention/admin/handlers/asterisk/waitingLoop.py", line 125, in __init__
    super(object, self).__init__(self, co, lo, position, dn, superordinate)
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 586, in __init__
    super(AsteriskBase, self).__init__(co, lo, position, dn, self.superordinate, attributes)
  File "%PY2.7%/univention/admin/handlers/__init__.py", line 596, in __init__
    self._validate_superordinate()
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 591, in _validate_superordinate
    super(AsteriskBase, self)._validate_superordinate()
  File "%PY2.7%/univention/admin/handlers/__init__.py", line 620, in _validate_superordinate
    if not set([self.superordinate.module]) & superordinate_names:
AttributeError: 'str' object has no attribute 'module'
```

**Comment by spaceone** [comment]
fixed with UCS 5.0
