### ISSUE TITLE
insufficientInformation: Kein übergeordnetes Objekt angegeben.

### ISSUE THREAD

**Issue by spaceone** [decoit/asterisk4ucs#22]
We received the following traceback feedback:

Version: 4.1-4 errata360 (Vahr)
Die Ausführung des Kommandos asteriskDeploy/create ist fehlgeschlagen:
```
Traceback (most recent call last):
  File "%PY2.7%/univention/management/console/base.py", line 281, in execute
    function(self, request)
  File "%PY2.7%/univention/management/console/modules/asteriskDeploy/__init__.py", line 70, in create
    createConfigs(log, server)
  File "%PY2.7%/univention/management/console/modules/asteriskDeploy/__init__.py", line 156, in createConfigs
    configs = univention.admin.handlers.asterisk.genConfigs(server)
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 532, in genConfigs
    'musiconhold.conf': genMusiconholdconf(co, lo, server),
  File "%PY2.7%/univention/admin/handlers/asterisk/__init__.py", line 269, in genMusiconholdconf
    for moh in music.lookup(co, lo, False):
  File "%PY2.7%/univention/admin/handlers/asterisk/music.py", line 147, in lookup
    superordinate=superordinate, attributes=attrs))
  File "%PY2.7%/univention/admin/handlers/asterisk/music.py", line 77, in __init__
    position, dn, superordinate)
  File "%PY2.7%/univention/admin/handlers/__init__.py", line 570, in __init__
    self._validate_superordinate()
  File "%PY2.7%/univention/admin/handlers/__init__.py", line 605, in _validate_superordinate
    raise univention.admin.uexceptions.insufficientInformation(_('No superordinate object given.'))
insufficientInformation: Kein übergeordnetes Objekt angegeben.
```

**Comment by spaceone** [comment]
fixed with UCS 5.0
