### ISSUE TITLE
Superordinate-Fehler beim Speichern von Objekten im LDAP

### ISSUE THREAD

**Issue by britter-decoit** [decoit/asterisk4ucs#5]
In der UDM zeigen wir den LDAP-Baum an und ermöglichen die Bearbeitung. Dabei tritt beim Speichern von Objekten folgendes Problem auf:

Die Ausführung des Kommandos asteriskDeploy/create ist fehlgeschlagen:
```
insufficientInformation: Kein übergeordnetes Objekt angegeben.
raise univention.admin.uexceptions.insufficientInformation()
File
"/usr/lib/pymodules/python2.7/univention/admin/handlers/_init__.py",
line 606, in validate_superordinate
self._validate_superordinate()
File
"/usr/lib/pymodules/python2.7/univention/admin/handlers/_init__.py",
line 571, in init
position, dn, superordinate)
File
"/usr/lib/pymodules/python2.7/univention/admin/handlers/asterisk/music.py",
line 77, in init
superordinate=superordinate, attributes=attrs))
File
"/usr/lib/pymodules/python2.7/univention/admin/handlers/asterisk/music.py",
line 147, in lookup
for moh in music.lookup(co, lo, False):
File
"/usr/lib/pymodules/python2.7/univention/admin/handlers/asterisk/__init__.py",
line 269, in genMusiconholdconf
'musiconhold.conf': genMusiconholdconf(co, lo, server),
File
"/usr/lib/pymodules/python2.7/univention/admin/handlers/asterisk/__init__.py",
line 532, in genConfigs
configs = univention.admin.handlers.asterisk.genConfigs(server)
File
"/usr/lib/pymodules/python2.7/univention/management/console/modules/asteriskDeploy/__init__.py",
line 156, in createConfigs
createConfigs(log, server)
File
"/usr/lib/pymodules/python2.7/univention/management/console/modules/asteriskDeploy/__init__.py",
line 70, in create
function(self, request)
File
"/usr/lib/pymodules/python2.7/univention/management/console/base.py",
line 281, in execute
Traceback (most recent call last):
```
Die Ausführung des Kommandos asteriskDeploy/create ist fehlgeschlagen

Wenn wir dieselben Objekte in "Domäne -> LDAP-Verzeichnis" im Unterzweig "Asterisk" bearbeiten, dann funktioniert das. Der einzige Unterschied zu dem Asterisk4UCS-Modul ist hierbei, dass im LDAP-Verzeichnis-Modul das Oberobjekt links markiert werden kann.

Intern als Bug #11022 verzeichnet.

**Comment by spaceone** [comment]
The regression was introduced by myself: https://forge.univention.org/bugzilla/show_bug.cgi?id=34764

**Comment by britter-decoit** [comment]
According to the bugtrack the fix should be targeted for 4.1.3. I updated this morning to 4.1.4 (4.1-4 errata 379) to see if the problem still occurs and it does :-(.

**Comment by spaceone** [comment]
Yes, this fix is responsible for the bug. I can also reproduce it, here is the traceback in more human readable:

```
Execution of command 'udm/add asterisk/asterisk' has failed:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/notifier/threads.py", line 82, in _run
    tmp = self._function()
  File "/usr/lib/pymodules/python2.7/notifier/__init__.py", line 104, in __call__
    return self._function( *tmp, **self._kwargs )
  File "/usr/lib/pymodules/python2.7/univention/management/console/modules/udm/__init__.py", line 367, in _thread
    dn = module.create(properties, container=options.get('container'), superordinate=options.get('superordinate'))
  File "/usr/lib/pymodules/python2.7/univention/management/console/modules/udm/udm_ldap.py", line 86, in _decorated
    return method(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/univention/management/console/ldap.py", line 141, in _decorated
    result = func(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/univention/management/console/modules/udm/udm_ldap.py", line 373, in create
    obj = self.module.object(None, ldap_connection, ldap_position, superordinate=superordinate)
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/asterisk/agiscript.py", line 86, in __init__
    position, dn, superordinate)
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/__init__.py", line 571, in __init__
    self._validate_superordinate()
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/__init__.py", line 606, in _validate_superordinate
    raise univention.admin.uexceptions.insufficientInformation(_('No superordinate object given.'))
insufficientInformation: No superordinate object given.
```

**Comment by britter-decoit** [comment]
Das Problem scheint nun behoben zu sein.

**Comment by spaceone** [comment]
Did you have a special look at phoneGroup objects? Do they behave like before? Is creation/modification possible via both LDAP tree and your module?
Are the same objects listed in the module as before? I don't know if phoneGroup objects and the server were listed there? Does it work with multiple phoneGroup objects?

**Comment by britter-decoit** [comment]
I had now. Saving does not work, I put the stacktrace in Bug #12.
